import {GTFont} from "@/app/font";
import Script from "next/script";
import "@/styles/global.scss"

export const metadata = {
  title: 'Wendor - TO-DO APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/8319204ada.js" crossOrigin="anonymous" />
      <body className={GTFont.className}>{children}</body>
    </html>
  )
}
